apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  {{ if .Values.mysqlRootPassword }}
  mysql-root-password: {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}